const os = require('os')
to get os system bit using os.arch() fun
console.log(os.arch())
console.log(os.cpus())
console.log(os.endianness())
console.log(os.hostname())
console.log(os.homedir())
console.log(os.platform())
console.log(os.release())
console.log(os.totalmem())
console.log(os.type())
console.log(os.uptime())
console.log(os.userInfo())
const freeMemory= os.freemem()
console.log(`${freeMemory/1024/1024}`)
const os = require('os')
const gettingTotalMemory = os.totalmem()
console.log(gettingTotalMemory)
